# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-07 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billboard_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Billboard_Post',
            new_name='Post',
        ),
    ]
