# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-10 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard_app', '0002_auto_20180207_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
