# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-10 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billboard_app', '0003_auto_20180210_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user_name',
            new_name='username',
        ),
    ]
