# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-10 20:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billboard_app', '0004_auto_20180210_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='username',
            new_name='user_name',
        ),
    ]
